{
    'name': 'Brainpack Meta WhatsApp Graph API',
    'version': '16.0.0',
    'author': 'BrainPack',
    'website': 'https://www.brainpack.io',
    'category': 'Base',
    'depends': ['base', 'mail', 'mail_group','base_automation'],
    'data': [
        'security/whatsapp_security.xml',
        'security/ir.model.access.csv',
        'data/cron.xml',
        'data/wa_template.xml',
        'wizard/wa_compose_message_view.xml',
        # 'views/res_config_settings_views.xml',
        'views/provider_base.xml',
        'views/res_users.xml',
        'views/channel_provider_line.xml',
        'views/res_partner.xml',
        'views/whatsapp_history.xml',
        'views/wa_template.xml',
        'views/variables.xml',
        'views/components.xml',
        'views/mail_channel.xml',
        'views/mail_message.xml',
        'views/provider_meta.xml',
        'views/ir_actions.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'brainpack_meta_whatsapp/static/src/css/style.css',
        ],
    },
    'installable': True,
    'auto_install': False,
    'license': 'LGPL-3',
}
