{
    "name": "Email tracking",
    "summary": "Email tracking system for all mails sent",
    "version": "16.0.1.0.0",
    "category": "Social Network",
    'website': 'https://www.brainpack.io',
    'author': 'BrainPack',
    "license": "AGPL-3",
    "application": False,
    "installable": True,
    "depends": ["mail","sale_management","crm","project"],
    "data": [
        "data/tracking_data.xml",
        "security/mail_tracking_email_security.xml",
        "security/ir.model.access.csv",
        "views/mail_tracking_email_view.xml",
        "views/mail_tracking_event_view.xml",
        "views/mail_message_view.xml",
        "views/res_partner_view.xml",
        "views/sale_order_view.xml",
        "views/crm_lead.xml",
        "views/project_project.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "mail_tracking/static/src/css/mail_tracking.scss",
            "mail_tracking/static/src/css/failed_message.scss",
            "mail_tracking/static/src/js/mail_tracking.esm.js",
            "mail_tracking/static/src/js/message.esm.js",
            "mail_tracking/static/src/js/failed_message/mail_failed_box.esm.js",
            "mail_tracking/static/src/js/failed_message/thread.esm.js",
            "mail_tracking/static/src/js/models/thread.esm.js",
            "mail_tracking/static/src/js/chatter.esm.js",
            "mail_tracking/static/src/js/discuss/discuss.esm.js",
            "mail_tracking/static/src/xml/mail_tracking.xml",
            "mail_tracking/static/src/xml/failed_message/common.xml",
            "mail_tracking/static/src/xml/failed_message/thread.xml",
            "mail_tracking/static/src/xml/failed_message/discuss.xml",
        ],

    },
    "demo": ["demo/demo.xml"],
}
